FROM golang:1.21.6 as builder

ARG ATLAS_URI

ENV APP_HOME /go/src/opportunity
ENV ATLAS_URI ${ATLAS_URI}
ENV GIN_MODE=release

WORKDIR "$APP_HOME"

COPY . .

RUN go mod download
RUN go build -tags=jsoniter -o opportunity

# copy build to a clean image
FROM golang:1.21.6

ARG ATLAS_URI

ENV APP_HOME /go/src/opportunity
ENV ATLAS_URI ${ATLAS_URI}
ENV GIN_MODE=release

RUN mkdir -p "$APP_HOME"
WORKDIR "$APP_HOME"

COPY --from=builder "$APP_HOME"/opportunity $APP_HOME

CMD ["./opportunity"]
